# Docker schema version definition
# Check the compatibility matrix with the current schema version in the File Creation Reference.
# https://docs.docker.com/compose/compose-file/
version: "3.8"

# Services or Containers List definition
services:
  mariadb:
    image: mariadb:10.6
    container_name: "database"
    restart: always
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - backend

networks:
  backend: