spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/haenggu
    username: haenggu_user
    password: haenggu1234*
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      max-file-size: 200MB # Max file size
      max-request-size: 215MB # Max Request size
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
file:
  upload-dir: ./uploaded_files